import type { OpenAPIV3 } from "openapi-types";

// This is a placeholder that gets replaced during build
// The actual OpenAPI paths are generated by the Vite plugin's closeBundle hook
const openApiSchemaPaths: OpenAPIV3.PathsObject = {};

export default openApiSchemaPaths;
